.idea/.name, .idea/compiler.xml, .idea/gradle.xml, .idea/misc.xml, .idea/vcs.xml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/repo01/repoapp/RepoApplication.kt, app/src/main/java/com/repo01/repoapp/data/network/GitHubService.kt, app/src/main/java/com/repo01/repoapp/di/ApiModule.kt
RepoApplication : Hilt 설정
ApiModule : 네트워크 관련 Hilt 설정
=> [ADD] - RepoApplicaion, ApiModule 클래스 추가

.idea/misc.xml, app/src/main/java/com/repo01/repoapp/ui/login/LoginActivity.kt, app/src/main/java/com/repo01/repoapp/ui/main/MainActivity.kt, app/src/main/res/drawable/bg_profile.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml
=> [ADD] - 메인액티비티로 이동 구현

.idea/misc.xml, app/src/main/java/com/repo01/repoapp/ui/main/MainActivity.kt, app/src/main/java/com/repo01/repoapp/ui/main/adapter/ViewPagerAdapter.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/issue/IssueFragment.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/notifications/NotificationsFragment.kt, app/src/main/res/drawable/bg_main_tab_selected.xml, app/src/main/res/drawable/bg_main_tab_selector.xml, app/src/main/res/drawable/bg_main_tab_unselected.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_issue.xml, app/src/main/res/layout/fragment_notifications.xml, app/src/main/res/layout/tab_main_title.xml, app/src/main/res/values/colors.xml
- TabLayout custom
- Issue, Notifications Fragment 이동 가능하게 연결
=> [FEAT] #4 #5 - 메인화면 탭 구현 및 프래그먼트 연결

.idea/misc.xml, app/src/main/java/com/repo01/repoapp/ui/login/LoginActivity.kt, app/src/main/java/com/repo01/repoapp/ui/login/LoginViewModel.kt, app/src/main/java/com/repo01/repoapp/util/Constants.kt, app/src/main/res/drawable/bg_main_tab_selected.xml, app/src/main/res/drawable/bg_main_tab_unselected.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml
- 인증과 관련된 스트링 값을 상수로 분리
- Uri 클래스 활용하여 스트링이 아닌 쿼리 파라미터로 값을 넘기도록 수정
- color drawable 이름 관련 버그 수정
=> [REFACTOR] 로그인 과정 리팩토링

.idea/misc.xml, app/src/main/java/com/repo01/repoapp/ui/main/tab/issue/IssueFragment.kt, app/src/main/res/drawable/custom_popup_background.xml, app/src/main/res/menu/menu_issue_filter.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml
필터 팝업 메뉴 나타나게 구현했습니다
보완 사항은 구현 방법 서치 후 해결해보도록 하겠습니다!
< 보완 사항 > 
- 팝업메뉴 & 필터바 사이 여백 문제
- 팝업 메뉴 전체 크기 조절 가능한지
- 선택/미선택 메뉴의 텍스트 색상 설정 로직 짜기
=> [ADD] #6 - 필터 팝업 메뉴 나타나게 구현

.idea/misc.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/repo01/repoapp/data/model/SearchItemModel.kt, app/src/main/java/com/repo01/repoapp/data/network/SearchService.kt, app/src/main/java/com/repo01/repoapp/data/network/TokenInterceptor.kt, app/src/main/java/com/repo01/repoapp/data/network/response/search/SearchResponse.kt, app/src/main/java/com/repo01/repoapp/data/repository/SearchRepository.kt, app/src/main/java/com/repo01/repoapp/di/ApiModule.kt, app/src/main/java/com/repo01/repoapp/ui/main/MainActivity.kt, app/src/main/java/com/repo01/repoapp/ui/search/SearchActivity.kt, app/src/main/java/com/repo01/repoapp/ui/search/SearchItemAdapter.kt, app/src/main/java/com/repo01/repoapp/ui/search/SearchViewModel.kt, app/src/main/res/drawable/bg_search_et_focused.xml, app/src/main/res/drawable/bg_search_et_normal.xml, app/src/main/res/drawable/bg_search_et_selector.xml, app/src/main/res/layout/activity_search.xml, app/src/main/res/layout/item_search_list.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
- 검색 화면 레이아웃
- 검색 API 호출
- 리사이클러뷰에 데이터 표출
=> [FEAT] 검색 기능 구현

app/src/main/java/com/repo01/repoapp/data/model/SearchItemModel.kt, app/src/main/java/com/repo01/repoapp/ui/search/SearchActivity.kt, app/src/main/java/com/repo01/repoapp/ui/search/SearchViewModel.kt, app/src/main/res/layout/activity_search.xml, app/src/main/res/layout/item_search_list.xml
- Timer를 사용하여, EditText의 내용이 변한 뒤 일정 시간 변경이 없으면 자동 검색
- star 갯수가 1100 이면 1.1k 로 표기
=> [FEAT, DESIGN] 텍스트 일정 시간 미입력시 자동 검색, star 갯수 format 적용

.idea/misc.xml, app/src/main/java/com/repo01/repoapp/ui/search/SearchActivity.kt, app/src/main/res/layout/activity_search.xml, app/src/main/res/values/strings.xml
검색 화면 툴바 추가
- navigation icon 클릭하면 액티비티 종료
=> [DESIGN] 검색 화면 툴바 추가

.idea/misc.xml, app/src/main/java/com/repo01/repoapp/data/model/IssueItemModel.kt, app/src/main/java/com/repo01/repoapp/data/network/IssueService.kt, app/src/main/java/com/repo01/repoapp/data/network/response/issue/IssueResponse.kt, app/src/main/java/com/repo01/repoapp/data/repository/IssueRepository.kt, app/src/main/java/com/repo01/repoapp/di/ApiModule.kt, app/src/main/java/com/repo01/repoapp/ui/main/MainActivity.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/issue/IssueFragment.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/issue/IssueViewModel.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/issue/adapter/IssueItemAdapter.kt, app/src/main/java/com/repo01/repoapp/util/PrintLog.kt, app/src/main/res/layout/fragment_issue.xml, app/src/main/res/layout/item_issue_list.xml, app/src/main/res/menu/menu_issue_filter.xml
- open / closed 상태에 따라 조회 가능하도록 구현했습니다 (all은 아직 미구현)
- all 타입 조회는 로직 고민 후 추가하도록 하겠습니다
- 받아온 데이터를 바인딩하는 부분 수정 예정입니다( 동작 확인을 위해 현재 클린하지 못하게 코드 작성되어 있음 )
=> [FEAT] - 이슈 데이터 조회 구현

.idea/misc.xml, app/src/main/java/com/repo01/repoapp/data/model/ProfileModel.kt, app/src/main/java/com/repo01/repoapp/data/network/ProfileService.kt, app/src/main/java/com/repo01/repoapp/data/network/response/profile/ProfileResponse.kt, app/src/main/java/com/repo01/repoapp/data/network/response/profile/StarredResponse.kt, app/src/main/java/com/repo01/repoapp/data/repository/ProfileRepository.kt, app/src/main/java/com/repo01/repoapp/di/ApiModule.kt, app/src/main/java/com/repo01/repoapp/ui/profile/ProfileActivity.kt, app/src/main/java/com/repo01/repoapp/ui/profile/ProfileViewModel.kt, app/src/main/res/layout/activity_profile.xml, app/src/main/res/layout/layout_profile_info.xml, app/src/main/res/values/strings.xml
- 프로필 조회를 위한 service, response 정의
- User API, Starring API 호출 
- 데이터 바인딩으로 화면에 표출 
- 프로필 정보 조회 시에 location, bio 등 값이 비었거나 null 인 경우는 아이템이 아예 화면에 보이지 않도록 설정했습니다.
=> [FEAT] 프로필 조회 기능 구현

.idea/misc.xml, app/src/main/res/drawable/bg_notifications_comment.xml, app/src/main/res/layout/item_notifications_list.xml
=> [DESIGN] #10 - notifications 리사이클러뷰 아이템뷰 레이아웃 구현

app/src/main/java/com/repo01/repoapp/ui/search/SearchActivity.kt, app/src/main/java/com/repo01/repoapp/ui/search/SearchViewModel.kt
- CoroutineScope.launch 는 Job 을 리턴
- 실행 중인 Job이 있으면 작업 취소하고 새로운 검색 작업 할당
=> [FIX] #17 - 일정 시간 미입력시 자동 검색, 코루틴 사용하는 방식으로 수정

app/src/main/java/com/repo01/repoapp/data/model/NotificationsInfoModel.kt, app/src/main/java/com/repo01/repoapp/data/model/NotificationsItemModel.kt, app/src/main/java/com/repo01/repoapp/data/model/OrganizationModel.kt, app/src/main/java/com/repo01/repoapp/data/model/SpecificIssueModel.kt, app/src/main/java/com/repo01/repoapp/data/network/IssueService.kt, app/src/main/java/com/repo01/repoapp/data/network/NotificationsService.kt, app/src/main/java/com/repo01/repoapp/data/network/OrganizationService.kt, app/src/main/java/com/repo01/repoapp/data/network/response/issue/SpecificIssueResponse.kt, app/src/main/java/com/repo01/repoapp/data/network/response/notifications/NotificationsInfoResponse.kt, app/src/main/java/com/repo01/repoapp/data/network/response/organization/OrganizationResponse.kt, app/src/main/java/com/repo01/repoapp/data/repository/IssueRepository.kt, app/src/main/java/com/repo01/repoapp/data/repository/NotificationsRepository.kt, app/src/main/java/com/repo01/repoapp/data/repository/OrganizationRepository.kt, app/src/main/java/com/repo01/repoapp/di/ApiModule.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/notifications/NotificationsFragment.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/notifications/NotificationsViewModel.kt, app/src/main/res/layout/fragment_notifications.xml, app/src/main/res/values/strings.xml
- nofications 조회 api 연동 및 필요한 데이터 수집 ( '사용자/저장소 이름' , '이슈 제목' , '업데이트 날짜')
- 위에서 얻은 데이터에서 repository name, issue number를 활용해 추가 데이터 수집
- repository name + issue number -> 특정 이슈 조회 후 코멘트 개수 가져오기
- repository name -> organization 정보 조회 후 이미지 url 가져오기
- 리스트를 순회하면서 각각 api 호출을 해야해서 coroutine async를 활용했습니다
=> [ADD] notifications 요구사항에 필요한 데이터 가져오기

app/src/main/java/com/repo01/repoapp/data/model/NotificationsItemModel.kt, app/src/main/java/com/repo01/repoapp/data/model/SpecificIssueModel.kt, app/src/main/java/com/repo01/repoapp/data/network/response/issue/SpecificIssueResponse.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/notifications/NotificationsFragment.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/notifications/NotificationsViewModel.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/notifications/adapter/NotificationsItemAdapter.kt, app/src/main/res/layout/fragment_notifications.xml, app/src/main/res/layout/item_notifications_list.xml, app/src/main/res/values/strings.xml
- api 통신으로 받아온 notifications 데이터 리사이클러뷰에 나타냈습니다
=> [FEAT] #13 - notifications 데이터 리사이클러뷰를 통해 나타내기

app/src/main/java/com/repo01/repoapp/data/repository/IssueRepository.kt, app/src/main/java/com/repo01/repoapp/ui/common/UiState.kt, app/src/main/java/com/repo01/repoapp/ui/login/LoginActivity.kt, app/src/main/java/com/repo01/repoapp/ui/login/LoginViewModel.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/issue/IssueFragment.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/issue/IssueViewModel.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/notifications/NotificationsViewModel.kt
- UiState sealed class를 생성해 데이터 통신 상태를 관리하도록 수정했습니다.
- IssueRepository에서 IssueViewModel로 통신 결과에 따른 UiState 를 반환하도록 했습니다.
=> [REFACTOR] 이슈 데이터 통신 시 sealed class로 ui 상태 관리

app/src/main/java/com/repo01/repoapp/data/network/NotificationsService.kt, app/src/main/java/com/repo01/repoapp/data/repository/NotificationsRepository.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/notifications/ItemTouchHelperListener.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/notifications/NotificationsFragment.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/notifications/NotificationsSwipeHelper.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/notifications/NotificationsViewModel.kt
- notifications 리사이클러뷰 스와이프 가능하게 구현했습니다 (ItemTouchHelper 사용)
- 스와이프 시 읽음 처리가 되도록 api 연동했습니다
< todo >
- 스와이프 후 화면에서 사라지도록 구현 예정입니다
=> [Feat] notifications swipe

app/src/main/java/com/repo01/repoapp/data/repository/SearchPagingSource.kt, app/src/main/java/com/repo01/repoapp/ui/search/SearchActivity.kt, app/src/main/res/layout/activity_search.xml
Paging의 LoadState를 통해 로딩 중일 때 progressBar를 보이게 합니다
=> [ADD] 로딩 중일 때 progressBar 표시

app/src/main/java/com/repo01/repoapp/ui/search/SearchActivity.kt, app/src/main/java/com/repo01/repoapp/ui/search/SearchViewModel.kt
- clear 버튼을 눌러 입력한 검색어를 지웁니다
- 사용자 입력이 500 ms 동안 멈추면 검색합니다
=> [FEAT] #17 - 입력 쿼리 삭제, debounce

app/build.gradle, app/src/main/java/com/repo01/repoapp/data/model/SearchItemModel.kt, app/src/main/java/com/repo01/repoapp/ui/search/SearchActivity.kt, app/src/main/java/com/repo01/repoapp/util/BindingAdapters.kt, app/src/main/res/layout/item_search_list.xml
- 언어별로 색상을 랜덤하게 적용합니다. 
- mutableMap을 사용해서 새로운 언어가 등장할 때 색상을 map에 추가적으로 저장하도록 했습니다!
- Glide를 사용해 프로필 이미지를 보여줍니다
=> [FEAT] 검색 결과 언어별 색상 적용 및 프로필 표시

app/src/main/java/com/repo01/repoapp/ui/main/MainActivity.kt, app/src/main/java/com/repo01/repoapp/ui/main/MainViewModel.kt, app/src/main/res/layout/activity_main.xml
=> [FEAT] 메인 화면에서 프로필 조회

app/src/main/res/layout/item_notifications_list.xml, app/src/main/res/values/strings.xml
- 레포지토리이름 뒤에 이슈번호 위치하도록 수정했습니다
=> [FIX] #58 - 노티피케이션 리사이클러뷰 이슈번호 위치 수정

app/src/main/java/com/repo01/repoapp/ui/main/tab/issue/IssueFragment.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/issue/IssueViewModel.kt
팝업 메뉴 선택 시 데이터 변경 과정을 뷰모델 내에서 처리하도록 수정했습니다
=> [REFACTOR] #58 - 이슈 팝업 메뉴 선택 시 데이터 처리 뷰모델에서 처리하도록 구현

app/src/main/res/layout/item_notifications_list.xml
- 지혜님이 구현해두신 바인딩 어댑터 사용해서 데이터 로드 시 이미지도 같이 불러오도록 추가했습니다
=> [ADD] - 알림 데이터 로드 시 이미지 불러오기 추가

app/src/main/java/com/repo01/repoapp/data/network/response/issue/IssueResponse.kt, app/src/main/java/com/repo01/repoapp/data/network/response/notifications/NotificationsInfoResponse.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/issue/adapter/IssueItemAdapter.kt, app/src/main/java/com/repo01/repoapp/ui/main/tab/notifications/adapter/NotificationsItemAdapter.kt, app/src/main/java/com/repo01/repoapp/util/DateCalculator.kt, app/src/main/res/layout/item_issue_list.xml, app/src/main/res/layout/item_notifications_list.xml
- 일수 기준으로 나타내게 구현했습니다
- 차이가 0일인 경우에는 "오늘" 로 나타냈습니다
=> [ADD] - 이슈, 알림 데이터 로드 시 날짜 계산 기능 추가

app/src/main/java/com/repo01/repoapp/data/repository/LoginRepository.kt, app/src/main/java/com/repo01/repoapp/ui/login/LoginActivity.kt, app/src/main/java/com/repo01/repoapp/ui/login/LoginViewModel.kt, app/src/main/java/com/repo01/repoapp/ui/main/MainActivity.kt, app/src/main/java/com/repo01/repoapp/ui/main/MainViewModel.kt, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/activity_main.xml
화면 전환
- Unit 타입의 LiveData 변수를 만들어 화면 이벤트를 관찰합니다
로그인 리팩토링
- 로그인을 UiState를 사용해 리팩토링했습니다
- 로딩 중이면 버튼 활성상태를 막습니다.
- 로그인 성공, 실패 시 알맞은 메시지를 Toast로 보여줍니다
=> [REFACTOR] 화면 전환 이벤트 데이터 바인딩 적용 및 로그인 리팩토링

app/src/main/java/com/repo01/repoapp/ui/main/tab/issue/IssueFragment.kt, app/src/main/res/drawable/ic_issue_menu_selector.xml, app/src/main/res/layout/fragment_issue.xml, app/src/main/res/menu/menu_issue_filter.xml, app/src/main/res/values/themes.xml
- 필터바와의 간격을 위해 팝업 메뉴 앵커뷰 수정
- 메뉴 checkableBehavior를 통해 선택한 메뉴에 체크 표시 기능 추가
=> [REFACTOR] #7 #31 - 팝업 메뉴 수정
